name: "Shared: SCA - Escaneo de vulnerabilidades"                                  
                                                                                                                                            
on:                                                                                
  workflow_call:                                                                   
                                                                                                     
jobs:                                                                                                          
  sca-scan:                                                                                                                                   
    runs-on: ubuntu-latest

    container:                                                                                                                                   
      image: aquasec/trivy:0.70.0
      options: --entrypoint /bin/sh
                                                                                     
    steps:                                                                                                                             
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: Ejecutar Trivy para escaneo de vulnerabilidades                                
        run: trivy fs --scanners vuln,secret,misconfig --exit-code 1 .
